### ISSUE TITLE
Release pre-trained models?

### ISSUE THREAD

**Issue by ufoym** [ducha-aiki/caffenet-benchmark#11]
This benchmark is really awesome!
Could you, if possible, release pre-trained caffe models?

**Comment by ducha-aiki** [comment]
Which ones? The most of them are pretty useless and consume lots of space. If you need some specific one, I can try to find them

**Comment by ufoym** [comment]
like 
- SqueezeNet128
- SqueezeNet128+ELU
- ResNet-50ELU-2xThinner

**Comment by ducha-aiki** [comment]
@ufoym 
ResNet-50ELU-2xThinner is here
https://github.com/ducha-aiki/caffenet-benchmark/releases/download/ResNet-50-ELU-2xThinner/ResNet56_lrwd_lsuv_elu_nobn_iter_320000.caffemodel
As for SqueezeNet128, I haven`t keep them, sorry.

**Comment by ufoym** [comment]
@ducha-aiki thx pretty much!

**Comment by ducha-aiki** [comment]
Here is freshly trained vgg16
https://github.com/ducha-aiki/caffenet-benchmark/releases/tag/vgg16_128

**Comment by ducha-aiki** [comment]
@ufoym  https://github.com/ducha-aiki/caffenet-benchmark/releases/tag/gln128_residual
