### ISSUE TITLE
Pre-trained GoogLeNet-128?

### ISSUE THREAD

**Issue by wangxianliang** [ducha-aiki/caffenet-benchmark#14]
Could you please release the pre-trained GoogLeNet-128 model?
Thanks a lot!

**Comment by ducha-aiki** [comment]
Unfortunately I cannot find it, probably, deleted at some of the disc cleaning sessions. :(

**Comment by wangxianliang** [comment]
How do you prepare the lmdb data? Do you resize the image to have the same width & height?

**Comment by ducha-aiki** [comment]
No, I resize image to 144xN keeping the aspect ratio, where N > 144.
It is done by image magick. And LMDB is used without resize flags 

```
#!/bin/bash
#usage: ./resize_to144_trim_no_aspect.sh input_dir 
DIR=$1
FILES=`find $1/ -maxdepth 5 -name "*.*"` # Base find command
for f in $FILES
do
  if [ -f $f ]; then
   mogrify -resize "144x144^" $f
  fi
done
```

**Comment by ducha-aiki** [comment]
@wangxianliang here is fresh vgg16-128
https://github.com/ducha-aiki/caffenet-benchmark/releases/tag/vgg16_128

**Comment by wangxianliang** [comment]
Great! Thanks a lot.

发件人: Dmytro Mishkin [mailto:notifications@github.com] 
发送时间: 2016年5月9日 18:21
收件人: ducha-aiki/caffenet-benchmark caffenet-benchmark@noreply.github.com
抄送: supercloud wangxianliang@outlook.com; Mention mention@noreply.github.com
主题: Re: [ducha-aiki/caffenet-benchmark] Pre-trained GoogLeNet-128? (#14)

@wangxianliang https://github.com/wangxianliang  here is fresh vgg16-128
https://github.com/ducha-aiki/caffenet-benchmark/releases/tag/vgg16_128
