### ISSUE TITLE
What about group in Caffenet and Alexnet

### ISSUE THREAD

**Issue by samson-wang** [ducha-aiki/caffenet-benchmark#21]
There is a 'group' param in Caffenet and Alexnet. I've googled a bit. It seams that no direct comparison between one group and two. Is it worth trying? Hope not too stupid.;-)
Thanks.

**Comment by ducha-aiki** [comment]
Hi,

It is already tested, see https://github.com/ducha-aiki/caffenet-benchmark/blob/master/Architectures.md

CaffeNet128, no group conv	0.487	2.26	Plain convolution instead group one
CaffeNet128	0.471	2.36	Pool5 = 3x3

**Comment by samson-wang** [comment]
Thank you! Sorry for missing that.
